{% set name = "bcrypt" %}
{% set version = "4.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 33313a1200a3ae90b75587ceac502b048b840fc69e7f7a0905b5f87fac7a1258

build:
  number: 0
  script:
    # PyPy has weird sysconfigdata name
    - rm -f $PREFIX/lib/pypy$PY_VER/_sysconfigdata.py  # [build_platform != target_platform and target_platform == "linux-ppc64le"]
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
  host:
    - python
    - pip
    - setuptools >=42.0.0
    - setuptools-rust
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - bcrypt
    - bcrypt._bcrypt
  requires:
    - pytest >=3.2.1,!=3.3.0
    - pip
  commands:
    - pytest tests
    - pip check

about:
  home: https://github.com/pyca/bcrypt/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Modern password hashing for your software and your servers
  description: |
    Modern password hashing for your software and your servers
  doc_url: https://github.com/pyca/bcrypt/
  dev_url: https://github.com/pyca/bcrypt/

extra:
  recipe-maintainers:
    - djsutherland
    - jan-janssen
    - xhochy
