{% set name = "bcrypt" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c59c170fc9225faad04dde1ba61d85b413946e8ce2e5f5f5ff30dfd67283f319

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cffi                                   # [build_platform != target_platform]
    - {{ compiler('c') }}
    - setuptools-rust
  host:
    - python
    - pip
    - cffi >=1.1
  run:
    - python
    - pip
    - cffi >=1.1
    - six >=1.4.1

test:
  source_files:
    - tests
  imports:
    - bcrypt
    - bcrypt._bcrypt
  requires:
    - pytest >=3.2.1,!=3.3.0
  commands:
    - pytest tests
    - pip check

about:
  home: https://github.com/pyca/bcrypt/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Modern password hashing for your software and your servers
  description: |
    Modern password hashing for your software and your servers
  doc_url: https://github.com/pyca/bcrypt/
  dev_url: https://github.com/pyca/bcrypt/

extra:
  recipe-maintainers:
    - djsutherland
    - jan-janssen
