{% set name = "bcrypt" %}
{% set version = "4.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 27d375903ac8261cfe4047f6709d16f7d18d39b1ec92aaf72af989552a650ebd

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: True  # [build_platform != "linux_ppc64le"]

requirements:
  build:
    script_env:
      - _PYTHON_SYSCONFIGDATA_NAME=_sysconfigdata__linux_ppc_64-linux-gnu  # [build_platform == "linux_ppc64le"]
    - {{ compiler('rust') }}
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
  host:
    - python
    - setuptools-rust
    - pip
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - bcrypt
    - bcrypt._bcrypt
  requires:
    - pip
    - pytest >=3.2.1,!=3.3.0
  commands:
    - pytest tests
    - pip check

about:
  home: https://github.com/pyca/bcrypt/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Modern password hashing for your software and your servers
  description: |
    Modern password hashing for your software and your servers
  doc_url: https://github.com/pyca/bcrypt/
  dev_url: https://github.com/pyca/bcrypt/

extra:
  recipe-maintainers:
    - djsutherland
    - jan-janssen
