schema_version: 1

context:
  name: bcrypt
  version: "5.0.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: f748f7c2d6fd375cc93d3fba7ef4a9e3a092421b8dbf34d8d4dc06be9492dfdd

build:
  number: 0
  script:
    # PyPy has weird sysconfigdata name
    - if: "build_platform != target_platform and target_platform == \"linux-ppc64le\""
      then: rm -f $PREFIX/lib/pypy$PY_VER/_sysconfigdata.py
    - if: unix
      then: export PYO3_USE_ABI3_FORWARD_COMPATIBILITY=1
      else: set PYO3_USE_ABI3_FORWARD_COMPATIBILITY=1
    - ${{ PYTHON }} -m pip install . --no-deps -vv
    - cd src/_bcrypt
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - pip
    - setuptools >=42.0.0
    - setuptools-rust
  run:
    - python

tests:
  - python:
      pip_check: true
      imports:
        - bcrypt
        - bcrypt._bcrypt
  - files:
      source:
        - tests
    requirements:
      run:
        - pytest >=3.2.1,!=3.3.0
    script:
      - pytest tests

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - src/_bcrypt/THIRDPARTY.yml
  summary: Modern password hashing for your software and your servers
  description: |
    Modern password hashing for your software and your servers
  homepage: https://github.com/pyca/bcrypt/
  repository: https://github.com/pyca/bcrypt/
  documentation: https://github.com/pyca/bcrypt/

extra:
  recipe-maintainers:
    - djsutherland
    - jan-janssen
    - xhochy
