travis:
  secure:
    BINSTAR_TOKEN: RE/m7bDKOUWz7Lt0o1Fav8c7KqpZgJCeJF2sH9VJbjoqOHf34rARn3pMGd6a/Uylb07PO4w/RVuiCeq+gEMvHY1PpofyUvgqqbjJ9UTQQRqUamncBrBIHQMb75Mj5P73xVmbXd+u+1WVSKMU5Dr74rqrxmia6qslLYFN0En+e3ylwe3jjXN532BSyB2wQHkv9q/ShucZ5MJDWhUxUzSke0aw6AmyItDBw4H0eo+MxJhGZ3EwldIO6b01CQwMIL4htaeA1vC+AgHVi8K12Ej2a81YL+zYODygveuPd44BtkagvT1JGdQBmyvocFJ54hpzqspvIR9yEBaGryzyByWQTkKFbgjisKodaTL78BJCGSRjadYxfgpp7xtBCBZvwrZVM7BQCKdcXaHNqhfFeolJJ9XExmJ6l98f5hAfRdG1d8hvLCfvBsOjTeSJ/VCsM3DM4w69R4vbh0mPEfc7LzK8l1sqVCC9FOrR3Tp5iYEk0j2hDAjon9QMzukc1Ycye3vc+6mAyvbiH4i9Yz8KkmwkGveyhzO0101VTf/gL30oyBaCyenPrRd+9DrSuL8hpUUOzURQUrfHGciCBkrlbBuAStfPz813khLKKZWxzyI1INlXnAaIPxcjMeC2iDIl3fmg/RABcf9KmZ8uUcXl8JwjYy49uU4hjvItWsebThre0y8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
